version: "3.9"
services:
  web:
    build:
        context: . 
        dockerfile: dockerfile
    image: go-app-ms:latest
    restart: always
    networks:
      - web
    ports:
      - "80:80"
    volumes:
      - .:/app
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: "redis:alpine"
volumes:
  logvolume01: {}

networks:
  web: